### ISSUE TITLE
Trying to run dmrshark on CentOS

### ISSUE THREAD

**Issue by EliosSs** [nonoo/dmrshark#1]
Hey nonoo, My name is Eliomar Conde, it's a pleasure to meet you.
I am trying to test dmrshark on CentOS, as you should know I have to modify the names of the libraries that the compiler uses and set some library paths for its correct execution.
I execute the program with sudo permissions (for pcap permissions) and I obtain segmentation fault.
Is that normal?

Where can I see a complete work example of the program?

I attach a picture of the error.

Regards.

![screenshot from 2018-08-11 21-51-45](https://user-images.githubusercontent.com/35732290/43997687-d137ab4a-9db0-11e8-950b-6caa67e3ecb1.png)

**Comment by nonoo** [comment]
Please use it with Debian. As far as I remember I haven't tried it with CentOS.

**Comment by EliosSs** [comment]
Oh ok. I understand then, thanks very much for the tip. 
I am already downloading DebianOS because i didn't have it.
Anyways, can you give me or tell me where is an example of how the software should work?
It will be helpful for a complete understanding from me.

Thanks in advance.

Reagrds. 
Eliomar Conde.

**Comment by nonoo** [comment]
I don't really know if it still works correctly, as if I remember correctly
the Hytera protocol has been changed. I haven't used dmrshark in the past 2
years.

--
Norbert Varga
http://www.nonoo.hu/

**Comment by EliosSs** [comment]
Ah ok ok. 
Well then I am on my own. =/
Thanks again for the help nonoo.
